AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  NacosAdapterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleArchitectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64

Outputs:
  NacosAdapterLayerArn:
    Value: !Ref NacosAdapterLayer
