AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-java

  Sample SAM Template for simple-java

Parameters:
  EFSAccessPointArn:
    Type: String
  EFSMountPath:
    Type: String
    Default: /mnt/efs
  SecurityGroups:
    Type: CommaDelimitedList
  SubnetIds:
    Type: CommaDelimitedList

Resources:
  NacosAdapterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layer

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java17
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -DJM.LOG.PATH=/tmp/nacos/logs -DJM.SNAPSHOT.PATH=/tmp/
          NACOS_SERVER_ADDRESS: localhost:8848
          NACOS_DATA_ID: !Ref NacosDataId
          NACOS_GROUP: !Ref NacosGroup
          AWS_LAMBDA_NACOS_ADAPTER_CONFIG_PATH: /mnt/efs/nacos
          RUST_LOG: debug
          # AWS_LAMBDA_EXEC_WRAPPER: /opt/sync-entry.sh # only for sync mode
          # AWS_LAMBDA_NACOS_ADAPTER_SYNC_PORT: 6666 # only for sync mode
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Layers:
        - !Ref NacosAdapterLayer
      FileSystemConfigs:
        - Arn: !Ref EFSAccessPointArn
          LocalMountPath: !Ref EFSMountPath
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroups
        SubnetIds: !Ref SubnetIds

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
